# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2fdd5dd55dfdd97ca4121d714d66f6e7ed96510b5750d5896c5c9c982b7dc2d806af628762543015166c6f702f53adeeb6d2b6f4ce40c0fb1b40df4978e6055

test:
  secret_key_base: af0306b34afb93c0ba3f34078a32f46499f7019884c7b3e905fe8d753e0cc7ea9f8276dca36713ef88acab9e261821f7a9723a6718876f3f8ab7e29b15e45602

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
